@AEHAFmtSender_HostAddress = http://localhost:5195
#http://localhost:5195
POST {{AEHAFmtSender_HostAddress}}/apiac
Content-Type: application/json
{
  "Power" : true, "OperationMode" : 88, "Degrees" : 26
}
###
